### ISSUE TITLE
移动端

### ISSUE THREAD

**Issue by ddddderek** [iweijie/react-web-highlight#3]
请问该库支持移动端嘛

**Comment by iweijie** [comment]
现在不支持， 需要改写下事件的触发方式 ，这块之前想做， 后续没有需求就停滞了   ...

**Comment by leejunhui** [comment]
如果能支持移动端就太完美了😄

**Comment by leejunhui** [comment]
> 现在不支持， 需要改写下事件的触发方式 ，这块之前想做， 后续没有需求就停滞了 ...

最近项目中遇到了在 h5 页面中划线标注和笔记的需求，想请教一下如果要让 react-web-highlight 支持移动端的话改造成本高吗？以及如果要支持移动端的话的一个改造思路是怎么样的呢？十分感谢~

**Comment by iweijie** [comment]
![image](https://user-images.githubusercontent.com/24514961/204832847-d99fcec9-cb6d-4833-a365-c82977f2d6e4.png)

@leejunhui  现有的事件是在pc端  mouseup 去判断是否有选中的文本，  移动端这边事件的触发可能会有所不同

**Comment by leejunhui** [comment]
> ![image](https://user-images.githubusercontent.com/24514961/204832847-d99fcec9-cb6d-4833-a365-c82977f2d6e4.png)
> 
> @leejunhui 现有的事件是在pc端 mouseup 去判断是否有选中的文本， 移动端这边事件的触发可能会有所不同

感谢回复~ 这个库支持移动端的长按手势 https://github.com/luojilab/easy-marker，但是它的高亮和划线不是在原本的文字的 DOM 结构上，而是一个 svg 盖在了文字的上面，这样就会造成调整文字大小之后，高亮和划线位置错误。我再尝试看看能不能结合 easy-marker 和 react-web-highlight 实现一下

**Comment by leejunhui** [comment]
@iweijie 在借鉴了您的 react-web-highlight 的核心代码后，结合 easy-marker 的长按手势识别，最终达到了理想的效果👍🏻
